### ISSUE TITLE
invalid request error on any transaction attempt

### ISSUE THREAD

**Issue by giunatale** [Pylons-tech/LOUD#78]
I have downloaded the app to try it out (OnePlus Nord, Android 11, Oxygen OS 11.1.2.AC01BA), but I can't seem to be able to get anything going.

I have tried creating a character, converting pylons to gold, or making a trade but I always get:

```
invalid request: The recipe doesn't exist: failed to execute message; message index: 0
```

Perhaps, if needed, I can help debug the issue if you direct me to what you would need to fetch.

As a side note: I believe the "get Pylons" button in the "Settings" tab could be gamed to get infinite Pylons, and even at this early stage should be limited (it seemed to me it is not) to a fixed number of times. (Perhaps make it unlimited only for specific dev-wallets?)

**Comment by MikeSofaer** [comment]
Hi! This is unfortunately down because of the Stargate upgrade, I will look into whether I can put up a temporary server.

The "get Pylons" is a testnet function, main net won't have it :)

**Comment by giunatale** [comment]
I will close the issue then, as it is not really a valid one. Thanks for the quick reply!
